### ISSUE TITLE
How do I find the DisplayProductID and DisplayVendorID?

### ISSUE THREAD

**Issue by vincentcox** [comsysto/Display-Override-PropertyList-File-Parser-and-Generator-with-HiDPI-Support-For-Scaled-Resolutions#1]
The build in tool "System information" doesn't provide that information :/

**Comment by clouless** [comment]
It is all written here:

https://comsysto.github.io/Display-Override-PropertyList-File-Parser-and-Generator-with-HiDPI-Support-For-Scaled-Resolutions/

Just scroll down to

![detect](https://cloud.githubusercontent.com/assets/12599965/17496274/ccd2ff4a-5dbc-11e6-9ef3-b6b30450f487.jpg)

And if you need more help you can ask in the [tonymacx86.com forum](http://www.tonymacx86.com/threads/adding-using-hidpi-custom-resolutions.133254/)

**Comment by vincentcox** [comment]
I am ashamed that I looked over that... My apologies...

**Comment by clouless** [comment]
It always happens to me as well on many pages, that I don't scroll down 😄
